### ISSUE TITLE
Working after big update already? 

### ISSUE THREAD

**Issue by Dragonflyss** [Lafko/Launcher#9]
Hi! Is it already working after the last big update?

**Comment by nicocf23** [comment]
Not working yet, all the developers working so hard to solve it asap.

**Comment by praisethemoon** [comment]
Hello! I am actually interested in contributing but I have no idea about this *hacking* world, any idea how to get started?

**Comment by brandont1** [comment]
Hopefully it gets resolved

**Comment by ugur21ay** [comment]
how much time does it take?

**Comment by seekerliu** [comment]
xRadar is working now.

**Comment by AllStaRRRz** [comment]
Thanks for Information about xRadar but we need to use Lafkos Launcher :P

**Comment by ugur21ay** [comment]
I do not try

**Comment by seekerliu** [comment]
It means other radars will be updated soon.

**Comment by brandont1** [comment]
Anyone have a link for xradar or is this one up yet?

**Comment by ugur21ay** [comment]
other radars have not been updated yet

**Comment by GiannisMaster** [comment]
Is it working?

**Comment by ugur21ay** [comment]
no is not working

**Comment by AllStaRRRz** [comment]
Hmm Lafko is maybe Busy on the last time. No comment regarding his launcher. Let us wait for Big Suprise about the Launcher Update in a few days. Stay Tuned

**Comment by nicocf23** [comment]
Lafko only made the Launcher, the radars are made by others, just Albedo, VM, and JS...and they are still outdate. Only Damncheaters radar working. And it cost so much money for a radar. If you want to play with it, just pay it. If not, play without radars. Is much better, lol. I was only using radar for  loot items, not for enemies! Because you waste many time looting, and with item radar reduce it a lot!! 😂

**Comment by praisethemoon** [comment]
I thought so as well, this is only a front or another radar idk which is. I saw many threads on elitepvpers where they mention that the paid radars are just a front for open source ones, primarily gaydar. I think that's why its author marked the repo as archived. He does the work, they get paid for it.

**Comment by GiannisMaster** [comment]
fixed?

**Comment by ugur21ay** [comment]
?????

**Comment by Lafko** [comment]
Stop spam
